const Anthropic = require("@anthropic-ai/sdk");
const { corsHeaders } = require("../shared/helpers");

module.exports = async function (context, req) {
  if (req.method === "OPTIONS") {
    context.res = { status: 204, headers: corsHeaders(req) };
    return;
  }

  try {
    const { tasks, context: ctx } = req.body;

    if (!tasks || !Array.isArray(tasks)) {
      context.res = {
        status: 400,
        headers: corsHeaders(req),
        body: JSON.stringify({ ok: false, error: "tasks array required" })
      };
      return;
    }

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      context.res = {
        status: 500,
        headers: corsHeaders(req),
        body: JSON.stringify({ ok: false, error: "ANTHROPIC_API_KEY not configured" })
      };
      return;
    }

    // Prepare task summary for AI
    const taskSummary = tasks.map(t => ({
      id: t.id,
      status: t.status,
      description: t.description || "",
      phase: t.phase || "",
      workstream: t.workstream || "",
      executor: t.executor || "",
      blocker: t.blocker || "",
      startDate: t.startDate || "",
      endDate: t.endDate || "",
      dependencies: (t.dependencies || []).length > 0 ? t.dependencies.join(", ") : "none"
    }));

    // Build context description
    let contextDesc = "";
    if (ctx?.focusDate) {
      contextDesc += `Focus Date: ${ctx.focusDate}\n`;
    }
    if (ctx?.focusMode) {
      contextDesc += `Focus Mode: ${ctx.focusMode}\n`;
    }
    if (ctx?.phaseFilter && ctx.phaseFilter !== "all") {
      contextDesc += `Phase Filter: ${ctx.phaseFilter}\n`;
    }
    if (ctx?.generatedBy) {
      contextDesc += `Generated by: ${ctx.generatedBy}\n`;
    }

    // Call Anthropic API
    const anthropic = new Anthropic({ apiKey });

    const prompt = `You are a project manager creating a concise standup summary for an M3 ERP cutover migration.

${contextDesc ? `Context:\n${contextDesc}\n` : ""}
Tasks (${tasks.length} total):
${JSON.stringify(taskSummary, null, 2)}

Generate a brief standup summary (3-5 sentences) covering:
1. Overall progress (how many tasks completed, in progress, blocked)
2. Key blockers or risks (if any)
3. Notable upcoming tasks or dependencies
4. Any critical actions needed

Keep it concise and actionable for a daily standup meeting.`;

    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 1024,
      messages: [{
        role: "user",
        content: prompt
      }]
    });

    const summary = message.content[0].text;

    context.res = {
      status: 200,
      headers: { ...corsHeaders(req), "Content-Type": "application/json" },
      body: JSON.stringify({ ok: true, summary })
    };

  } catch (e) {
    context.log.error("Summary generation error:", e);
    context.res = {
      status: 500,
      headers: corsHeaders(req),
      body: JSON.stringify({ ok: false, error: e.message || "Failed to generate summary" })
    };
  }
};
